name: flipme_app
description: An app which exhibits data from a GraphQL API

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  auto_route: ^1.0.2
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1
  provider: ^5.0.0
  flutter_native_splash: ^1.1.7+1
  flutter_launcher_icons: ^0.9.0
  desktop_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2

# to run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFB648"
  image: "assets/graphics/fliper.png"
  fullscreen: true

# to run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/graphics/fliper.png"

flutter:
  uses-material-design: true