name: flipme_app
description: An app which exhibits data from a GraphQL API

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.0
  graphql: ^5.0.0-nullsafety.4
  hive: ^2.0.3
  hive_flutter: ^1.0.0  
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1
  provider: ^5.0.0
  flutter_native_splash: ^1.1.7+1
  flutter_launcher_icons: ^0.9.0
  desktop_window: ^0.4.0
  # pixel_perfect: ^1.0.9
  envify: ^2.0.0
  intl: ^0.17.0
  flip_card: ^0.5.0
  fl_chart: ^0.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  envify_generator: ^2.0.0
  hive_generator: ^1.0.1
  lint: ^1.5.3

# to run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFB648"
  image: "assets/graphics/fliper.png"
  fullscreen: true

# to run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/graphics/fliper.png"

flutter:
  uses-material-design: true
  assets:
    - assets/designs/
    - assets/fonts/
    - assets/graphics/    
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800